package script

import (
	"github.com/Foxcapades/lib-go-raml-types/v0/pkg/raml"
	"github.com/Foxcapades/lib-go-raml-types/v0/pkg/raml/rmeta"
	"github.com/Foxcapades/lib-go-raml-types/v0/pkg/raml/rparse"
	"github.com/sirupsen/logrus"
	"gopkg.in/yaml.v3"
	"os"
	"strings"
)

const generated = `
################################################################################
#                                                                              #
#  DO NOT EDIT THIS FILE; IT WAS GENERATED AUTOMATICALLY.                      #
#  CHANGES MADE HERE WILL BE LOST.                                             #
#                                                                              #
################################################################################

`

func ProcessRaml(path string) string {
	stat, err := os.Stat(path)
	if err == os.ErrNotExist {
		logrus.Fatalf("Provided path does not exist: %s", path)
	} else if err != nil {
		logrus.Fatalf("Could not stat path %s: %s", path, err)
	}

	if !stat.IsDir() {
		logrus.Fatalf("Provided path is not a directory: %s", path)
	}

	files := getFiles(path)
	libs := make(map[string]raml.Library, len(files))

	for file := range files {
		f, err := os.Open(file)
		if err != nil {
			logrus.Fatalf("Could not read %s: %s", file, err)
		}

		lib, err := rparse.ParseLibrary(f)
		if err != nil {
			logrus.Fatalf("Could not parse %s: %s", file, err)
		}
		libs[file] = lib
	}

	out := strings.Builder{}
	out.WriteString(rmeta.HeaderLibrary)
	out.WriteString(generated)

	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)

	if err := enc.Encode(merge(files, libs)); err != nil {
		logrus.Fatal(err)
	}

	return out.String()
}
