name: Release

on:
  push:
    tags:
    - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.24

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: go test -v ./...

    - name: Build Release Binaries
      run: make release

    - name: Publish Binaries
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        files: |
          bin/merge-raml-darwin.${{ github.ref_name }}.tar.gz
          bin/merge-raml-linux.${{ github.ref_name }}.tar.gz
          bin/merge-raml-windows.${{ github.ref_name }}.zip
        generate_release_notes: true